name: Fuzz Parser

on:
  push:
    branches: [master]
    paths:
      - src/parser.c
  pull_request:
    paths:
      - src/parser.c

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run fuzzer
        uses: tree-sitter/fuzz-action@v4
